# Network name, architecture
model: 
  network_name: 'NN1'
  hidden_dim_list: [10,10]
  
# Training parameters
training: 
  max_epochs: 1000
  learning_rate: 0.001
  batch_size: 50
  dropout: 0.0
  patience_length: 5
  checkout_epochs: [100,200,400] 

# Data files
data: 
  data_dir: ["C:\\Users\\G71044MH\\OneDrive - The University of Manchester\\Documents\\GitHub\\Ethogram\\Neural Data Analysis\\PoissonNN\\data\\mouse2_poissonNN_prepped_data_extinction.mat"]

